[package]
name = "nucleo_l152re"
version = "0.1.0"
edition = "2021"
description = "Board support for STM Nucleo-L152RE."

[dependencies]
cortex_m = { path = "../../../arch/cortex-m" }
kernel = { path = "../../../kernel" }
stm32l152ret6 = { path = "../../../mcu/stm32/stm32l152ret6" }
specs = { workspace = true }