###########################################################
### Responsible for linking all crates in the workspace ###
###########################################################

[workspace]
resolver = "2"

# Builds RTOS lib for target provided
default-members = [
    "macros/entry",
    "specs",
    "kernel",
]

# Builds **EXAMPLES** using the RTOS lib
members = [
    "macros/entry",
    "specs",
    "kernel",
    "arch/cortex-m",
    "bsp/nucleo/nucleo_l152re",
    "phase_testing/phase0/no_rtos_basic",
    "phase_testing/phase2/pendsv_pending_probe",
    "phase_testing/phase2/primitive_switch",
    "phase_testing/phase2/psp_to_psp",
    "phase_testing/phase2/p2_stack_guard",
    "phase_testing/phase3/systick_tick_probe",
    "phase_testing/phase3/multi_task_auto",
    "phase_testing/phase3/priority_delay_demo",
    "phase_testing/phase3/all_tasks_delay_demo",
    "phase_testing/phase3/five_task_priority_demo",
]

[workspace.dependencies]
toml = "0.8"
specs = { path = "specs" }

# No unwinding allowed for panic handlers
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
