###########################################################
### Responsible for linking all crates in the workspace ###
###########################################################

[workspace]
resolver = "2"

# Builds RTOS lib for target provided
default-members = [
    # "kernel",
    # "specs",
    # TODO: add drivers, arch and board specifics here
    # "arch/*",             # add target architecture when ready
    # "drivers/*",          # add target drivers when ready
    # "boards/*",           # add target board when ready
]

# Builds **EXAMPLES** using the RTOS lib
members = [
    "examples/phase0/no_rtos_basic",
    # "kernel",
    # "specs",
    # TODO: add drivers, arch and board specifics here
    # "arch/*",             # add when ready
    # "drivers/*",          # add when ready
    # "boards/*",           # add when ready
]

# No unwinding allowed for panic handlers
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"