###########################################################
### Responsible for linking all crates in the workspace ###
###########################################################

[workspace]
resolver = "2"

# Builds RTOS lib for target provided
default-members = [
    "macros/entry",
    "specs",
    "kernel",
]

# Builds **EXAMPLES** using the RTOS lib
members = [
    "macros/entry",
    "specs",
    "kernel",
    "examples/phase0/no_rtos_basic",
    "bsp/nucleo/nucleo_l152re",
]

[workspace.dependencies]
toml = "0.8"
specs = { path = "specs" }

# No unwinding allowed for panic handlers
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"