[package]
name = "primitive_switch"
version = "0.1.0"
edition = "2021"
build = "../../../.cargo/build.rs"

[[bin]]
name = "primitive_switch"

[dependencies]
thetos_entry = { path = "../../../macros/thetos_entry" }
nucleo_l152re = { path = "../../../bsp/nucleo/nucleo_l152re" }
cortex_m = { path = "../../../arch/cortex-m" }
specs = { workspace = true }

[build-dependencies]
toml = { workspace = true }