[package]
name = "all_tasks_delay_demo"
version = "1.0.0"
edition = "2021"
build = "../../../.cargo/build.rs"

[[bin]]
name = "all_tasks_delay_demo"

[dependencies]
thetos_entry = { path = "../../../macros/thetos_entry" }
nucleo_l152re = { path = "../../../bsp/nucleo/nucleo_l152re" }
cortex_m = { path = "../../../arch/cortex-m" }

[build-dependencies]
toml = { workspace = true }
