[package]
name = "all_tasks_delay_demo"
version.workspace = true
edition.workspace = true
build = "../../../.cargo/build.rs"

[[bin]]
name = "all_tasks_delay_demo"

[dependencies]
thetos_entry = { path = "../../../macros/thetos_entry" }
nucleo_l152re = { path = "../../../bsp/nucleo/nucleo_l152re" }
cortex_m = { path = "../../../arch/cortex-m" }

[build-dependencies]
toml = { workspace = true }
