###########################################################
### Responsible for the kernel logic and scheduling logic ###
###########################################################

[package]
name = "kernel"
version = "1.0.0"
edition = "2021"

[dependencies]
specs = { workspace = true }
heapless = "0.9.2"