#################################################################################
### Responsible for configuring the build process for the target architecture ###
#################################################################################

