#################################################################################
### Responsible for configuring the build process for the target architecture ###
#################################################################################

[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags = ["-C", "link-arg=-Tboards/nucleo/nucleo-l152re/memory.x"]

[scripting]
gdb_instance = "arm-none-eabi-gdb"
openocd_interface = ""
openocd_target = ""